/**
 * Value Set SQL Utilities
 *
 * Generates SQL DDL and DML for populating a standalone `value_set_expansion`
 * table with code data loaded via the FHIR API.
 *
 * Use this when the HAPI FHIR JPA PostgreSQL view
 * (`scripts/hapi-fhir-sql-on-fhir/views/008_value_set_expansion_view.sql`)
 * is not available — for example when running against a plain PostgreSQL
 * database, DuckDB, or any other SQL environment that doesn't have HAPI.
 *
 * The table schema matches the view contract expected by the transpiler:
 *   code IN (SELECT code FROM value_set_expansion WHERE value_set_id = '<url>')
 */

import type { ValueSetExpansionRow } from './value-set-loader';

// ─── Constants ────────────────────────────────────────────────────────────────

const DEFAULT_TABLE = 'value_set_expansion';

/** Maximum rows per INSERT statement (avoids hitting parameter limits). */
const BATCH_SIZE = 500;

// ─── DDL ─────────────────────────────────────────────────────────────────────

/**
 * Generate `CREATE TABLE IF NOT EXISTS` DDL for a standalone value set
 * expansion table.  Schema is compatible with the HAPI FHIR JPA view.
 *
 * @param tableName  Table name (default: `value_set_expansion`)
 */
export function generateValueSetTableDdl(tableName = DEFAULT_TABLE): string {
  return [
    `-- Value set expansion table`,
    `-- Schema matches the value_set_expansion view from scripts/hapi-fhir-sql-on-fhir/`,
    `CREATE TABLE IF NOT EXISTS ${tableName} (`,
    `  value_set_id  TEXT        NOT NULL,`,
    `  code          TEXT        NOT NULL,`,
    `  system        TEXT        NOT NULL,`,
    `  display       TEXT,`,
    `  version       TEXT,`,
    `  PRIMARY KEY (value_set_id, system, code)`,
    `);`,
    ``,
    `CREATE INDEX IF NOT EXISTS idx_${tableName}_vs_id ON ${tableName} (value_set_id);`,
    `CREATE INDEX IF NOT EXISTS idx_${tableName}_code  ON ${tableName} (code);`,
  ].join('\n');
}

// ─── DML helpers ─────────────────────────────────────────────────────────────

function escSql(s: string | undefined): string {
  if (s === undefined || s === null) return 'NULL';
  return `'${s.replace(/'/g, "''")}'`;
}

function rowToValues(row: ValueSetExpansionRow): string {
  return (
    `(${escSql(row.value_set_id)}, ${escSql(row.code)}, ` +
    `${escSql(row.system)}, ${escSql(row.display)}, ${escSql(row.version)})`
  );
}

function buildInserts(
  rows: ValueSetExpansionRow[],
  tableName: string,
  conflictClause: string,
): string {
  if (rows.length === 0) return `-- No rows to insert into ${tableName}`;

  const stmts: string[] = [];
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    const values = batch.map(rowToValues).join(',\n  ');
    stmts.push(
      `INSERT INTO ${tableName} (value_set_id, code, system, display, version)\nVALUES\n  ${values}${conflictClause};`,
    );
  }
  return stmts.join('\n\n');
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate `INSERT INTO … VALUES …` SQL for a set of expansion rows.
 * Rows are batched into statements of up to 500 rows each.
 * Duplicate rows (same primary key) will cause an error — use
 * `generateValueSetUpsertSql` for idempotent loads.
 *
 * @param rows       Rows from `loadValueSetExpansions`
 * @param tableName  Target table (default: `value_set_expansion`)
 */
export function generateValueSetInsertSql(
  rows: ValueSetExpansionRow[],
  tableName = DEFAULT_TABLE,
): string {
  return buildInserts(rows, tableName, '');
}

/**
 * Generate `INSERT … ON CONFLICT DO NOTHING` SQL — safe to run multiple times.
 * Use this for idempotent seeding scripts or server boot sequences.
 *
 * @param rows       Rows from `loadValueSetExpansions`
 * @param tableName  Target table (default: `value_set_expansion`)
 */
export function generateValueSetUpsertSql(
  rows: ValueSetExpansionRow[],
  tableName = DEFAULT_TABLE,
): string {
  return buildInserts(rows, tableName, '\nON CONFLICT DO NOTHING');
}

/**
 * Generate a full standalone seed script that:
 *  1. Creates the table (if not exists)
 *  2. Upserts all expansion rows
 *
 * Suitable for use in a `psql -f seed.sql` workflow when the HAPI FHIR JPA
 * view-based approach is not available.
 *
 * @param rows       All expansion rows (combine `flatMap(r => r.rows)` from loader)
 * @param tableName  Target table (default: `value_set_expansion`)
 */
export function generateValueSetSeedScript(
  rows: ValueSetExpansionRow[],
  tableName = DEFAULT_TABLE,
): string {
  const uniqueValueSets = [...new Set(rows.map(r => r.value_set_id))];
  const header = [
    `-- Value set expansion seed script`,
    `-- Generated by @cqframework/elm-to-sql`,
    `-- Value sets: ${uniqueValueSets.length}`,
    `-- Total codes: ${rows.length}`,
    ``,
    `BEGIN;`,
    ``,
  ].join('\n');

  const ddl = generateValueSetTableDdl(tableName);
  const dml = generateValueSetUpsertSql(rows, tableName);

  return `${header}${ddl}\n\n${dml}\n\nCOMMIT;\n`;
}
